@url = http://localhost:4004/odata/v4/ticketingsystem
@auth = Basic alice:alice

# Get Tickets
GET {{url}}/Tickets
Authorization: {{auth}}


# Ein neues Ticket erstellen
POST {{url}}/Tickets
Authorization: {{auth}}
Content-Type: application/json

{
    "category": "CreateSubaccount",
    "projectManager": "John Doe",
    "description": "Test ticket description"
}
